config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :articles
  resources :comments,          only: [:create]
  get 'signup'  => 'users#new'
  get 'sessions/new'
  get    'login'   => 'sessions#new'
  get    'games'   => 'statics#juegos'
  get    'library'   => 'statics#library'
  get    'games/game'   => 'statics#game'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root 'statics#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :subtitle, presence: true
  validates :content, presence: true
  validates :user_id, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :book
  belongs_to :game
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
  validates :user_id, presence: true, length: { maximum: 150 }
  validates :content, presence: true, length: { maximum: 1500 }
  validates :article_id, presence: true

  default_scope -> { order(:created_at) }
end

app/models/dice_system.rb
class DiceSystem < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :comments
  has_many :articles

  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 20 }, uniqueness: { case_sensitive: false }
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 8 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  include SessionsHelper

  private

  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      redirect_to login_url
    end
  end




end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    @articles =  Article.paginate(:page => params[:page], :per_page => 3)

  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
    username
    @comment = @article.comments.build
    @comments = @article.comments.paginate(page: params[:page], :per_page => 3)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    if logged_in?
      @article = current_user.articles.build(article_params)
      if @article.save
       redirect_to @article
      else
        render 'new'
      end
    else
    redirect_to root_url
    end
  end

  def username
    @author = User.find(@article.user_id)

  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :subtitle, :content, :user_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in_user, only: [:create]

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      @confirm = "published!"

      redirect_to :back
    else
      @confirm = "Se ha producido un problema"

    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :article_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create

    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_url
    else
      @message = 'Invalid email/password combination'
      render 'new'
    end
  end


  def destroy
    log_out
    redirect_to root_url
  end

  def update
    if @current_user.nil?
      redirect_to root_url
    else
      redirect_to root_url
    end
  end


end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def index
    @print_articles = Article.last(5)
  end

  def games
  end

  def game
  end

  def library
  end

  def get_articles
    @print_articles = Article.last(5)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    if current_user && current_user.id == 1
      @users = User.all
    else
      redirect_to root_url
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end

  end



  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Roll&Rol la mejor web de rol en español"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if @current_user.nil?
      @current_user = User.find_by(id: session[:user_id])
    else
      @current_user
    end
  end


  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end


end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end


end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>

    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

          <ul>
            <% @article.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

  <div >
    <%= f.label 'Título' %><br>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label 'Subtítulo' %><br>
    <%= f.text_field :subtitle %>
  </div>
  <div>
    <%= f.label 'Artículo' %><br>
    <%= f.text_area :content, cols: "100%", rows: "10"  %>

  </div>
  <div>
    <%= f.submit 'Enviar' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<% provide(:place, 'article') %>

<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% provide(:place, 'article') %>


<%= link_to 'Escribe un artículo', new_article_path, class: 'add-link' %>


  <% @articles.each do |article| %>

      <article class="col-xs-12 no-padding">

        <%= link_to(image_tag('mouse-guard-set.jpg', class: 'col-xs-3 pull-left img-responsive art-image'), article) %>
        <div class="col-xs-9">
          <h2>
            <%= link_to article.title, article %></h2>
          <h4 class="subtitle"><%= article.subtitle %></h4>
          <hr>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque dignissim nec nisl non
          vehicula. Sed justo eros, gravida quis ex vitae, efficitur porta purus. Nunc volutpat, est
          vitae pellentesque tincidunt, metus sem euismod orci, et accumsan nibh tellus et quam. Praesent
          vulputate nunc id elit tristique, a fringilla tellus luctus. Mauris eget mauris sit amet elit
          scelerisque ornare sed vitae mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque dignissim nec nisl non
          vehicula. Sed justo eros, gravida quis ex vitae, efficitur porta purus.
        </div>

      </article>

  <% end %>

  <br>

  <div class="center">
    <div class="pagination">
      <%= will_paginate @article %>

    </div>
  </div>

app/views/articles/new.html.erb
<% provide(:place, 'article') %>

<h1>Escribe un artículo</h1>
<br>
<p>
<%= render 'form' %>
</p>
<%= link_to 'Volver', articles_path, class: 'right add-link' %>

app/views/articles/show.html.erb
<% provide(:place, 'article') %>
<h1>
  <%= @article.title %>
</h1>
<hr>
<h3 class="subtitle"><%= @article.subtitle %></h3>
<p>Por: <%= link_to @author.name, @author %></p>
<p>
  <%= @article.content %>
</p>
<%= image_tag("car-three.png", class: 'col-xs-6 img-responsive pull-right image-art') %>


<%= link_to "Volver", articles_path %>

<div class="rating">
  <form>
            <span class="star-rating" id="star">
                <input type="radio" name="rating" class="star" value="1"><i></i>
                <input type="radio" name="rating" class="star" value="2"><i></i>
                <input type="radio" name="rating" class="star" value="3"><i></i>
                <input type="radio" name="rating" class="star" value="4"><i></i>
                <input type="radio" name="rating" class="star" value="5"><i></i>
            </span><br/>

    <b class="puntuacion">
      Puntuar artículo
    </b>
  </form>
</div>
<hr>
<h3>Comentarios (<%= @article.comments.count %>)</h3>
<% if @article.comments.any? %>
    <ol>
      <%= render @comments %>
    </ol>
    <div class="center">
       <%= will_paginate @comments %>
      </div>
<% end %>

<hr>

<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<div class="comment">
  <div class="user-info-comment">
    <%= link_to(image_tag('user_avatar.png'), comment.user) %>

    <br>
    <%= link_to comment.user.name, comment.user %>
    <br><%= time_ago_in_words(comment.user.created_at) %>
  </div>

  <div class="user-comment">
    <p>
      <%= comment.content %>
    </p>

  </div>
  <div class="rating">
    <form class="vote">
      <input type="radio" name="rating" value="up"><i></i>
      <input type="radio" name="rating" value="down"><i></i>
    </form>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
    <%= f.hidden_field :article_id, :integer => @article.id %>
    <div>
      <%= f.label 'Añadir comentario' %><br>
      <%= f.text_area :content, placeholder: "Escribe tu comentario...", cols: "100%", rows: "10" %>
    </div><p>
    <%= f.submit "Enviar", class: "right" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>

  <%= stylesheet_link_tag 'bootstrap', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'jquery-ui.min', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>



  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  <%= javascript_include_tag 'isotope-docs.min', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery-ui.min', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="
<% if yield(:place) == "index" %>
    index-body
<% end %>
">

<% if yield(:place) != "index" %>
<div class="row">
<% end %>

<nav class="up-nav" id="index-nav">
      <span class="col-md-4 col-md-push-5" id="loginsystem">

  <% if logged_in? %>
    <%= link_to current_user.name, current_user %>
            |
            <%= link_to "Cerrar sesión", logout_path, method: :delete %>
  <% else %>
    <%= link_to "Inicia sesión", login_path %>
            |
            <%= link_to "Regístrate", signup_path %>
  <% end %>
    </span>
  <a class="pull-right" href="/"><span class="glyphicon glyphicon-plus"></span></a>

  <div class="box-search col-md-3">
    <span class="glyphicon glyphicon-search"></span>

    <form id="buscador">
      <input type="search" class="form-control" placeholder="Búsqueda..."/>
    </form>
  </div>

</nav>
<% if yield(:place) != "index"  %>
  </div>
<% end %>

<div class="loginbox">

  <a class="close">x</a>


  <label for="usuario">Usuario:</label>
  <input type="text" id="usuario" required="required">

  <br/>
  <label for="password">Contraseña:</label>
  <input type="password" id="password" required="required">

  <p>

    <button id="iniciosesion">Enviar</button>

  </p>
</div>

<% if yield(:place) != "index"  %>


    <div class="row">
      <main>

        <div id="dice"></div>


        <div class="web-title">
          <a href="/"><h1 class="web-title">Roll&Rol</h1></a>
        </div>

        <div class="content">
          <nav class="col-md-3 no-padding arrow">
            <% if yield(:place) == "article"  %>
                <%= link_to "Artículos", articles_path, id: 'active' %>
            <% else %>
            <%= link_to "Artículos", articles_path %>
             <% end %>
            <% if yield(:place) == "game"  %>
                <a href="/games" id="active">Juegos</a>
            <% else %>
                <a href="/games">Juegos</a>
            <% end %>
            <% if yield(:place) == "foros"  %>
                <a href="/boards" id="active">Foros</a>
            <% else %>
                <a href="/boards">Foros</a>
            <% end %>
            <% if yield(:place) == "library"  %>
                <a href="/library" id="active">Librería</a>
            <% else %>
                <a href="/library">Librería</a>
            <% end %>


          </nav>
          <article class="col-xs-9">
<% end %>

<%= yield %>

<% if yield(:place) != "index"  %>
</article>
    </div>
    </main>
    </div>
    <footer class="row">
      <span class="left">© 2015 - www.Roll&Rol.com</span>
      <span class="right"><a href="/">Quienes somos</a></span>
    </footer>


<% end %>

</body>

</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/statics/index.html.erb
<%= stylesheet_link_tag 'index.css', 'data-turbolinks-track' => true %>

<% provide(:place, 'index') %>

<div id="dice"></div>
<header id="web-banner">
</header>



<main id="index">

  <div class="web-title"><h1 class="web-title">Roll&Rol</h1></div>
  <div class="row">


    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>

      <div class="carousel-inner" role="listbox">
        <div class="item active slider-size">
                                <span class="carousel-caption">
                                    Lorem ipsum dolor sit amet consectetur </span>
          <%= image_tag("car-one.png") %>
        </div>

        <div class="item slider-size">
          <div class="carousel-caption">Lorem ipsum dolor sit amet, consectetur</div>
          <%= image_tag("car-two.jpg") %>
        </div>

        <div class="item slider-size">
          <div class="carousel-caption">Lorem ipsum dolor sit amet, consectetur</div>
          <%= image_tag("car-three.jpg") %>
        </div>


      </div>

      <!-- Left and right controls -->
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

  </div>
  <div class="row">
    <section class="col-md-4 info-4">

      <%= link_to 'Artículos', articles_path, class: 'sec-title' %>

           <% @print_articles.each do |item|%>
          <p>
            <%= link_to item.title, item %>
            <%= item.subtitle %>
          </p>
          <hr>
          <% end%>

    </section>


    <section class="col-md-4 info-4">
      <a href="#"><h1>Últimos juegos</h1></a>

      <p><a href="juego.html">Lorem ipsum</a> dolor sit amet, consectetur adipiscing elit. Nullam...
      </p>
      <hr>
      <p><a href="juego.html">Lorem ipsum</a> dolor sit amet, consectetur adipiscing elit. Nullam...
      </p>
      <hr>
      <p><a href="juego.html">Lorem ipsum</a> dolor sit amet, consectetur adipiscing elit. Nullam...
      </p>
      <hr>
      <p><a href="juego.html">Lorem ipsum</a> dolor sit amet, consectetur adipiscing elit. Nullam...
      </p>
      <hr>
      <p><a href="juego.html">Lorem ipsum</a> dolor sit amet, consectetur adipiscing elit. Nullam...
      </p><hr>


    </section>


    <section class="col-md-4 info-4">
      <a href="#"><h1>Foros</h1></a>

      <p><a href="/">Lorem ipsum</a> dolor sit amet, consectetur adipiscing elit. Nullam...
      </p>
      <hr>
      <p><a href="/">Lorem ipsum</a> dolor sit amet, consectetur adipiscing elit. Nullam...
      </p>
      <hr>
      <p><a href="/">Lorem ipsum</a> dolor sit amet, consectetur adipiscing elit. Nullam...
      </p>
      <hr>
      <p><a href="/">Lorem ipsum</a> dolor sit amet, consectetur adipiscing elit. Nullam...
      </p>
      <hr>
      <p><a href="/">Lorem ipsum</a> dolor sit amet, consectetur adipiscing elit. Nullam...
      </p><hr>

    </section>
  </div>

  <div class="row">
    <section class="col-md-12 info-12">

      <a href="library"><h1>¿Buscas nuestra librería?</h1></a>
      <%= image_tag("v_masquerade.jpg", :class => "img-responsive pull-right cover-img") %>

      <h2>Lorem ipsum</h2>

      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac nisi egestas, viverra ligula nec,
        lobortis massa.
        Curabitur vestibulum orci id turpis fringilla, ac consectetur risus condimentum. Nam porttitor
        condimentum fermentum.
        Aliquam sollicitudin volutpat efficitur. Nunc non consequat quam. Nam feugiat in nulla sed suscipit.
        Maecenas non ultricies justo. In hac habitasse platea dictumst.
        Etiam at ante accumsan, pretium nulla vitae, varius arcu.
        Aenean eu tempus magna. Duis vehicula ex facilisis accumsan sollicitudin.
      </p>

      <div class="center"><br/>
        <button id="button" onclick="location.href='library'">Ver Librería</button>
      </div>
    </section>
  </div>

  <div class="row">


    <hr>

    <section class="info-12 center">


      <%= image_tag("award.png", :class => "col-xs-1 pull-left img-responsive") %>
      <%= image_tag("award.png", :class => "col-xs-1 hidden-xs pull-right img-responsive") %>


      <h2>Lorem ipsum</h2>

      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac nisi egestas, viverra ligula nec,
        lobortis massa. Curabitur vestibulum orci id turpis fringilla, ac consectetur risus condimentum.
      </p>
    </section>
  </div>
</main>


<div class="row">
  <footer class="col-md-12 index">
    <span class="left">© 2015 - www.Roll&Rol.com</span>
    <span class="right"><a href="/">Quienes somos</a></span>
  </footer>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Back', @user %> |

app/views/users/index.html.erb
    <h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>New</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Registro</h1>

    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>
<p>
        <%= f.label "Nombre de usuario"%><br>
        <%= f.text_field :name %>

</p><p>
        <%= f.label "Correo electrónico" %><br>
        <%= f.email_field :email %>
    </p><p>
        <%= f.label "Contraseña" %><br>
        <%= f.password_field :password %>
</p><p>
        <%= f.label :password_confirmation, "Repite tu contraseña" %><br>
        <%= f.password_field :password_confirmation %>
</p><p>
        <%= f.submit "Registrarme" %></p>
    <% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>
<% if current_user.id == @user.id %>
<%= link_to "Edit", edit_user_path(@user) %>
<%end%>